wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.78
    framework: huggingface
    huggingface_version: 4.48.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.11.2
    start_time: 1738237568.36983
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      3:
      - 13
      - 23
      4: 3.11.2
      5: 0.13.78
      6: 4.48.1
      8:
      - 5
